Removed postgres timeout

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,16 +6,16 @@ jobs:
       - image: circleci/golang:1.8	# for App Registry
     steps:
       - checkout
-      - run:
-          name: Waiting for Postgres to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z localhost 5432 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for Postgres && exit 1
+      #- run:
+      #  name: Waiting for Postgres to be ready
+      #  command: |
+      #    for i in `seq 1 10`;
+      #    do
+      #      nc -z localhost 5432 && echo Success && exit 0
+      #      echo -n .
+      #      sleep 1
+      #    done
+      #    echo Failed waiting for Postgres && exit 1
       - run: pip install -r python_demo/requirements.txt
       - run:
           name: Run unit tests
